<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<UseWPF>true</UseWPF>
		<RootNamespace>Muggle.TsExtensions.Demo1</RootNamespace>
		<Configurations>D2021;D2024;R2021;R2024</Configurations>
        <Optimize Condition="$(Configuration.StartsWith('R'))">True</Optimize>
        <DefineConstants Condition="$(Configuration.StartsWith('D'))">TRACE;DEBUG</DefineConstants>
        <DefineConstants Condition="$(Configuration.StartsWith('R'))">TRACE;RELEASE</DefineConstants>
	</PropertyGroup>
    
	<ItemGroup>
		<PackageReference Include="CalcBinding" />
		<PackageReference Include="Muggle.TsExtensions.CodingHelper" Condition="$(Configuration.StartsWith('R'))" />
		<PackageReference Include="Tekla.Structures" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Datatype" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Dialog" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Model" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Plugins" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodingHelper\CodingHelper.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"
                          Condition="$(Configuration.StartsWith('D'))" />
		<ProjectReference Include="..\Common.WPF\Common.WPF.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(TargetDir)$(TargetName).dll&quot; &quot;D:\Program Files\Tekla Structures\$(TeklaVersion)\Environments\common\extensions\Muggle.TsExtensions\&quot; /Y /C /Q /R" />
	</Target>

</Project>
