<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="CalcBinding" Version="2.5.2" />
		<PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
		<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
		<PackageVersion Include="Muggle.TsExtensions.CodingHelper" Version="2.0.0-beta.4" />
		<PackageVersion Include="Tekla.Structures" Version="$(TeklaVersion)" />
		<PackageVersion Include="Tekla.Structures.Catalogs" Version="$(TeklaVersion)" />
		<PackageVersion Include="Tekla.Structures.Datatype" Version="$(TeklaVersion)" />
		<PackageVersion Include="Tekla.Structures.Dialog" Version="$(TeklaVersion)" />
		<PackageVersion Include="Tekla.Structures.Model" Version="$(TeklaVersion)" />
		<PackageVersion Include="Tekla.Structures.Plugins" Version="$(TeklaVersion)" />
		<PackageVersion Include="TeklaStructuresAttributes" Version="1.0.5" />
		<PackageVersion Include="TSAppConfigPatcherTask" Version="2.1.3" Condition="$(Configuration.EndsWith('2024'))" />
	</ItemGroup>
</Project>