/*==============================================================================
 *  Muggle TsExtensions - extensions for Tekla Structures
 *
 *  Copyright © 2026 Huang YongXing.
 *
 *  This library is free software, licensed under the terms of the GNU
 *  General Public License as published by the Free Software Foundation,
 *  either version 3 of the License, or (at your option) any later version.
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *==============================================================================
 *  PluginFieldDefaultValuesGenerator.cs: help to generate set data to default method for plugin.
 *  written by Huang YongXing - thinkerhua@hotmail.com
 *==============================================================================*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Muggle.TsExtensions.CodingHelper.Generators.Information;
using static Muggle.TsExtensions.CodingHelper.Generators.GeneratorHelper;

namespace Muggle.TsExtensions.CodingHelper.Generators;

[Generator]
internal class PluginFieldDefaultValuesGenerator : IIncrementalGenerator {
    internal static readonly string[] ConcernedAttributes = [
        "Muggle.TsExtensions.CodingHelper.Generators.PartFieldDefaultValuesAttribute",
        "Muggle.TsExtensions.CodingHelper.Generators.PlateFieldDefaultValuesAttribute",
        "Muggle.TsExtensions.CodingHelper.Generators.WeldFieldDefaultValuesAttribute",
        "Muggle.TsExtensions.CodingHelper.Generators.BoltFieldDefaultValuesAttribute",
        "Muggle.TsExtensions.CodingHelper.Generators.BoltCircleFieldDefaultValuesAttribute",
    ];

    /// <summary>
    /// Dictionary of preset values.
    /// <list type="bullet">
    ///     <item>Key - attribute short name, such as "PartFieldDefaultValuesAttribute".</item>
    ///     <item>Value - dictionary of field name and preset value.
    ///         <list type="bullet">
    ///             <item>Key - field name, such as "profile".</item>
    ///             <item>Value - preset value.</item>
    ///         </list>
    ///     </item>
    /// </list>
    /// </summary>
    private ReadOnlyDictionary<string, ReadOnlyDictionary<string, string>> PresetValues { get; }

    #region Templates

    private const string PartialClassTemplate =
        """
        //  <auto-generated/>{{generatedAt}}

        namespace {{namespace}} {

            {{accessibility}} partial {{typeKind}}class {{className}} {
        {{method}}
            }
        }

        """;

    private const string SetDataToDefaultMethodTemplate =
        """
                
                /// <summary>
                /// Set data (fields) to default value if they are not setted from user interface.
                /// </summary>
                private void SetDataToDefaultIfUnset() {
        {{statements}}
                }
        """;

    private const string PartSetToDefaultStatementsTemplate =
        """
                    
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Profile))
                        {{dataPropertyName.}}{{modelObjectName}}Profile = "{{profileValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Material))
                        {{dataPropertyName.}}{{modelObjectName}}Material = "{{materialValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Name))
                        {{dataPropertyName.}}{{modelObjectName}}Name = "{{nameValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Finish))
                        {{dataPropertyName.}}{{modelObjectName}}Finish = "{{finishValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Class))
                        {{dataPropertyName.}}{{modelObjectName}}Class = {{classValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AssemblyPrefix))
                        {{dataPropertyName.}}{{modelObjectName}}AssemblyPrefix = "{{assemblyPrefixValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AssemblyStartNumber))
                        {{dataPropertyName.}}{{modelObjectName}}AssemblyStartNumber = {{assemblyStartNumberValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PartPrefix))
                        {{dataPropertyName.}}{{modelObjectName}}PartPrefix = "{{partPrefixValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PartStartNumber))
                        {{dataPropertyName.}}{{modelObjectName}}PartStartNumber = {{partStartNumberValue}};
        """;

    private const string PlateSetToDefaultStatementsTemplate =
        """
                    
                    if ({{dataPropertyName.}}{{modelObjectName}}Thickness <= 0)
                        {{dataPropertyName.}}{{modelObjectName}}Thickness = {{thicknessValue}};
                    if ({{dataPropertyName.}}{{modelObjectName}}Breadth <= 0)
                        {{dataPropertyName.}}{{modelObjectName}}Breadth = {{breadthValue}};
                    if ({{dataPropertyName.}}{{modelObjectName}}Height <= 0)
                        {{dataPropertyName.}}{{modelObjectName}}Height = {{heightValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Material))
                        {{dataPropertyName.}}{{modelObjectName}}Material = "{{materialValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Name))
                        {{dataPropertyName.}}{{modelObjectName}}Name = "{{nameValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Finish))
                        {{dataPropertyName.}}{{modelObjectName}}Finish = "{{finishValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Class))
                        {{dataPropertyName.}}{{modelObjectName}}Class = {{classValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AssemblyPrefix))
                        {{dataPropertyName.}}{{modelObjectName}}AssemblyPrefix = "{{assemblyPrefixValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AssemblyStartNumber))
                        {{dataPropertyName.}}{{modelObjectName}}AssemblyStartNumber = {{assemblyStartNumberValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PartPrefix))
                        {{dataPropertyName.}}{{modelObjectName}}PartPrefix = "{{partPrefixValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PartStartNumber))
                        {{dataPropertyName.}}{{modelObjectName}}PartStartNumber = {{partStartNumberValue}};
        """;

    private const string WeldSetToDefaultStatementsTemplate =
        """
                    
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}TypeAbove))
                        {{dataPropertyName.}}{{modelObjectName}}TypeAbove = {{typeAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}TypeBelow))
                        {{dataPropertyName.}}{{modelObjectName}}TypeBelow = {{typeBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SizeAbove))
                        {{dataPropertyName.}}{{modelObjectName}}SizeAbove = {{sizeAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SizeBelow))
                        {{dataPropertyName.}}{{modelObjectName}}SizeBelow = {{sizeBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AngleAbove))
                        {{dataPropertyName.}}{{modelObjectName}}AngleAbove = {{angleAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}AngleBelow))
                        {{dataPropertyName.}}{{modelObjectName}}AngleBelow = {{angleBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ContourAbove))
                        {{dataPropertyName.}}{{modelObjectName}}ContourAbove = {{contourAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ContourBelow))
                        {{dataPropertyName.}}{{modelObjectName}}ContourBelow = {{contourBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}FinishAbove))
                        {{dataPropertyName.}}{{modelObjectName}}FinishAbove = {{finishAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}FinishBelow))
                        {{dataPropertyName.}}{{modelObjectName}}FinishBelow = {{finishBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RootFaceAbove))
                        {{dataPropertyName.}}{{modelObjectName}}RootFaceAbove = {{rootFaceAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RootFaceBelow))
                        {{dataPropertyName.}}{{modelObjectName}}RootFaceBelow = {{rootFaceBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}EffectiveThroatAbove))
                        {{dataPropertyName.}}{{modelObjectName}}EffectiveThroatAbove = {{effectiveThroatAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}EffectiveThroatBelow))
                        {{dataPropertyName.}}{{modelObjectName}}EffectiveThroatBelow = {{effectiveThroatBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RootOpeningAbove))
                        {{dataPropertyName.}}{{modelObjectName}}RootOpeningAbove = {{rootOpeningAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RootOpeningBelow))
                        {{dataPropertyName.}}{{modelObjectName}}RootOpeningBelow = {{rootOpeningBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}IncrementAmountAbove))
                        {{dataPropertyName.}}{{modelObjectName}}IncrementAmountAbove = {{incrementAmountAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}IncrementAmountBelow))
                        {{dataPropertyName.}}{{modelObjectName}}IncrementAmountBelow = {{incrementAmountBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}LengthAbove))
                        {{dataPropertyName.}}{{modelObjectName}}LengthAbove = {{lengthAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}LengthBelow))
                        {{dataPropertyName.}}{{modelObjectName}}LengthBelow = {{lengthBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PitchAbove))
                        {{dataPropertyName.}}{{modelObjectName}}PitchAbove = {{pitchAboveValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PitchBelow))
                        {{dataPropertyName.}}{{modelObjectName}}PitchBelow = {{pitchBelowValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Around))
                        {{dataPropertyName.}}{{modelObjectName}}Around = {{aroundValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Shop))
                        {{dataPropertyName.}}{{modelObjectName}}Shop = {{shopValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Placement))
                        {{dataPropertyName.}}{{modelObjectName}}Placement = {{placementValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Preparation))
                        {{dataPropertyName.}}{{modelObjectName}}Preparation = {{preparationValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Intermittent))
                        {{dataPropertyName.}}{{modelObjectName}}Intermittent = {{intermittentValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ReferenceText))
                        {{dataPropertyName.}}{{modelObjectName}}ReferenceText = "{{referenceTextValue}}";
        """;

    private const string BoltSetToDefaultStatementsTemplate =
        """
                    
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Size))
                        {{dataPropertyName.}}{{modelObjectName}}Size = {{sizeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Standard))
                        {{dataPropertyName.}}{{modelObjectName}}Standard = "{{standardValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}DistXText))
                        {{dataPropertyName.}}{{modelObjectName}}DistXText = "{{distXTextValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}DistYText))
                        {{dataPropertyName.}}{{modelObjectName}}DistYText = "{{distYTextValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Type))
                        {{dataPropertyName.}}{{modelObjectName}}Type = {{typeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ThreadInMaterial))
                        {{dataPropertyName.}}{{modelObjectName}}ThreadInMaterial = {{threadInMaterialValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}CutLength))
                        {{dataPropertyName.}}{{modelObjectName}}CutLength = {{cutLengthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ExtraLength))
                        {{dataPropertyName.}}{{modelObjectName}}ExtraLength = {{extraLengthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Tolerance))
                        {{dataPropertyName.}}{{modelObjectName}}Tolerance = {{toleranceValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PlainType))
                        {{dataPropertyName.}}{{modelObjectName}}PlainType = {{plainTypeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}BlindHoleDepth))
                        {{dataPropertyName.}}{{modelObjectName}}BlindHoleDepth = {{blindHoleDepthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole1))
                        {{dataPropertyName.}}{{modelObjectName}}Hole1 = {{hole1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole2))
                        {{dataPropertyName.}}{{modelObjectName}}Hole2 = {{hole2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole3))
                        {{dataPropertyName.}}{{modelObjectName}}Hole3 = {{hole3Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole4))
                        {{dataPropertyName.}}{{modelObjectName}}Hole4 = {{hole4Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole5))
                        {{dataPropertyName.}}{{modelObjectName}}Hole5 = {{hole5Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}HoleType))
                        {{dataPropertyName.}}{{modelObjectName}}HoleType = {{holeTypeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SlottedHoleX))
                        {{dataPropertyName.}}{{modelObjectName}}SlottedHoleX = {{slottedHoleXValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SlottedHoleY))
                        {{dataPropertyName.}}{{modelObjectName}}SlottedHoleY = {{slottedHoleYValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RotateSlots))
                        {{dataPropertyName.}}{{modelObjectName}}RotateSlots = {{rotateSlotsValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}IsBolt))
                        {{dataPropertyName.}}{{modelObjectName}}IsBolt = {{isBoltValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseNut1))
                        {{dataPropertyName.}}{{modelObjectName}}UseNut1 = {{useNut1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseNut2))
                        {{dataPropertyName.}}{{modelObjectName}}UseNut2 = {{useNut2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher1))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher1 = {{useWasher1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher2))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher2 = {{useWasher2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher3))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher3 = {{useWasher3Value}};
        """;

    private const string BoltCircleSetToDefaultStatementsTemplate =
        """
                    
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Size))
                        {{dataPropertyName.}}{{modelObjectName}}Size = {{sizeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Standard))
                        {{dataPropertyName.}}{{modelObjectName}}Standard = "{{standardValue}}";
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}NumberOfBolts))
                        {{dataPropertyName.}}{{modelObjectName}}NumberOfBolts = {{numberOfBoltsValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Diameter))
                        {{dataPropertyName.}}{{modelObjectName}}Diameter = {{diameterValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Type))
                        {{dataPropertyName.}}{{modelObjectName}}Type = {{typeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ThreadInMaterial))
                        {{dataPropertyName.}}{{modelObjectName}}ThreadInMaterial = {{threadInMaterialValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}CutLength))
                        {{dataPropertyName.}}{{modelObjectName}}CutLength = {{cutLengthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}ExtraLength))
                        {{dataPropertyName.}}{{modelObjectName}}ExtraLength = {{extraLengthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Tolerance))
                        {{dataPropertyName.}}{{modelObjectName}}Tolerance = {{toleranceValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}PlainType))
                        {{dataPropertyName.}}{{modelObjectName}}PlainType = {{plainTypeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}BlindHoleDepth))
                        {{dataPropertyName.}}{{modelObjectName}}BlindHoleDepth = {{blindHoleDepthValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole1))
                        {{dataPropertyName.}}{{modelObjectName}}Hole1 = {{hole1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole2))
                        {{dataPropertyName.}}{{modelObjectName}}Hole2 = {{hole2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole3))
                        {{dataPropertyName.}}{{modelObjectName}}Hole3 = {{hole3Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole4))
                        {{dataPropertyName.}}{{modelObjectName}}Hole4 = {{hole4Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}Hole5))
                        {{dataPropertyName.}}{{modelObjectName}}Hole5 = {{hole5Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}HoleType))
                        {{dataPropertyName.}}{{modelObjectName}}HoleType = {{holeTypeValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SlottedHoleX))
                        {{dataPropertyName.}}{{modelObjectName}}SlottedHoleX = {{slottedHoleXValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}SlottedHoleY))
                        {{dataPropertyName.}}{{modelObjectName}}SlottedHoleY = {{slottedHoleYValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}RotateSlots))
                        {{dataPropertyName.}}{{modelObjectName}}RotateSlots = {{rotateSlotsValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}IsBolt))
                        {{dataPropertyName.}}{{modelObjectName}}IsBolt = {{isBoltValue}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseNut1))
                        {{dataPropertyName.}}{{modelObjectName}}UseNut1 = {{useNut1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseNut2))
                        {{dataPropertyName.}}{{modelObjectName}}UseNut2 = {{useNut2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher1))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher1 = {{useWasher1Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher2))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher2 = {{useWasher2Value}};
                    if (IsDefaultValue({{dataPropertyName.}}{{modelObjectName}}UseWasher3))
                        {{dataPropertyName.}}{{modelObjectName}}UseWasher3 = {{useWasher3Value}};
        """;

    #endregion

    public PluginFieldDefaultValuesGenerator() {
        var dict = new Dictionary<string, ReadOnlyDictionary<string, string>>();

        foreach (var text in GetAttributeSourceTexts(ConcernedAttributes)) {
            var defaultValues =
                GetDefaultValuesFromSyntaxTree(CSharpSyntaxTree.ParseText(text), out string attributeName);
            dict.Add(attributeName, new ReadOnlyDictionary<string, string>(defaultValues));
        }

        PresetValues = new ReadOnlyDictionary<string, ReadOnlyDictionary<string, string>>(dict);

    }

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(ctx => {
            foreach (var attribute in ConcernedAttributes) {
                var shortName = attribute.Substring(attribute.LastIndexOf('.') + 1);
                ctx.AddSource($"{shortName}.g.cs",
                    SourceText.From(GetResourceAsString($"{shortName}.cs"), Encoding.UTF8));
            }
        });

        var provider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform)
            .Where(x => x != default);

        context.RegisterSourceOutput(provider, Generate);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken token) {
        if (token.IsCancellationRequested) return false;

        if (node is not ClassDeclarationSyntax classDeclarationSyntax ||
            !classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword)) return false;

        if (classDeclarationSyntax.AttributeLists.Count > 0) return true;

        return classDeclarationSyntax.Members.Any(member =>
            member switch {
                FieldDeclarationSyntax { AttributeLists.Count: > 0 } or
                    PropertyDeclarationSyntax { AttributeLists.Count: > 0 } => true,
                _ => false
            });
    }

    private PluginFieldDefaultValuesInfo Transform(GeneratorSyntaxContext context, CancellationToken token) {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclarationSyntax);
        if (classSymbol == null) return default;

        AttributeSyntax[] attributeSyntaxes = null;
        AttributeSyntax[] fieldsFromAttSyntax = null;
        AttributeTargets appliedTarget = default;
        string targetMemberName = null;
        ITypeSymbol dataType = null;
        var placeCnt = 0;

        if (TryGetMatchedAttributes(classDeclarationSyntax.AttributeLists, semanticModel,
                ConcernedAttributes, ref attributeSyntaxes)) {
            //  When applied on class, the FieldsFromAttribute must also be applied
            if (!TryGetMatchedAttributes(classDeclarationSyntax.AttributeLists, semanticModel,
                    ["Muggle.TsExtensions.CodingHelper.Generators.FieldsFromAttribute"],
                    ref fieldsFromAttSyntax)) {
                return default;
            }

            placeCnt++;
            appliedTarget = AttributeTargets.Class;

            var expression = (TypeOfExpressionSyntax)fieldsFromAttSyntax.Single().ArgumentList!.Arguments[0].Expression;
            dataType = semanticModel.GetTypeInfo(expression.Type).Type;
        }

        _ = classDeclarationSyntax.Members.Where(member => {
            if (member is FieldDeclarationSyntax fieldSyntax &&
                TryGetMatchedAttributes(fieldSyntax.AttributeLists, semanticModel,
                    ConcernedAttributes, ref attributeSyntaxes)) {
                placeCnt++;
                appliedTarget = AttributeTargets.Field;

                targetMemberName = fieldSyntax.Declaration.Variables[0].Identifier.ValueText;
                dataType = semanticModel.GetTypeInfo(fieldSyntax.Declaration.Type).Type;

                return true;
            }

            if (member is PropertyDeclarationSyntax propertySyntax &&
                TryGetMatchedAttributes(propertySyntax.AttributeLists, semanticModel,
                    ConcernedAttributes, ref attributeSyntaxes)) {
                placeCnt++;
                appliedTarget = AttributeTargets.Property;

                targetMemberName = propertySyntax.Identifier.ValueText;
                dataType = semanticModel.GetTypeInfo(propertySyntax.Type).Type;

                return true;
            }

            return false;

        }).ToArray();

        // no attribute or applied on over one place
        if (placeCnt != 1) return default;

        var dataTypePluginDataFieldsAttributeArguments = dataType.GetAttributes().Where(a =>
                PluginDataFieldsGenerator.ConcernedAttributes.Contains(a.AttributeClass?.ToDisplayString()))
            .Select(a => {
                var attName = a.AttributeClass!.ToDisplayString();
                attName = attName.Substring(attName.LastIndexOf('.') + 1);
                var attArgs = a.ConstructorArguments
                    .SelectMany(argArray => argArray.Values.Select(arg => arg.Value!.ToString()))
                    .OrderBy(s => s).ToArray();
                return (attName, attArgs);
            }).OrderBy(t => t.attName).ToArray();

        var attDict = new ArgumentsDictionary<DefaultValueDictionary>();

        foreach (var attSyntax in attributeSyntaxes) {
            var attTypeInfo = semanticModel.GetTypeInfo(attSyntax);
            var attQualifiedName = attTypeInfo.Type!.ToDisplayString();
            var attName = attQualifiedName.Substring(attQualifiedName.LastIndexOf('.') + 1);

            if (!attDict.TryGetValue(attName, out DefaultValueDictionary elementDict)) {
                elementDict = new DefaultValueDictionary();
                attDict.Add(attName, elementDict);
            }

            var argSyntaxes = attSyntax.ArgumentList?.Arguments;
            if (argSyntaxes == null) continue;

            var valueDict = new Dictionary<string, string>();

            string nameOrNumber = string.Empty;
            var index = -1;
            foreach (var argSyntax in argSyntaxes) {
                index++;

                var paramName = argSyntax.NameColon?.Name.Identifier.ValueText;
                var paramValue = ((LiteralExpressionSyntax)argSyntax.Expression).Token.ValueText;

                if (paramName == null && index == 0 ||
                    paramName != null &&
                    Regex.Match(paramName, "(part|plate|weld|bolt|boltCircle)N(ame|umber)").Success) {
                    nameOrNumber = paramValue;
                    continue;
                }

                paramName ??= PresetValues[attName].ElementAt(index - 1).Key;
                valueDict.Add(paramName, paramValue);
            }

            if (string.IsNullOrEmpty(nameOrNumber)) continue;
            if (elementDict.ContainsKey(nameOrNumber)) continue;

            //  data doesnt have these fields
            if (!dataTypePluginDataFieldsAttributeArguments.Any(t =>
                    t.attName.Substring(0, t.attName.Length - 10) == attName.Substring(0, attName.Length - 22) &&
                    t.attArgs.Contains(nameOrNumber))) {
                continue;
            }

            elementDict.Add(nameOrNumber, valueDict);
        }

        if (attDict.Count == 0) return default;

        token.ThrowIfCancellationRequested();

        return new PluginFieldDefaultValuesInfo {
            ClassInfo = new ClassInfo {
                Name = classDeclarationSyntax.Identifier.Text,
                NameSpace = classSymbol.ContainingNamespace.ToDisplayString(),
                Accessibility = classSymbol.DeclaredAccessibility,
                IsRecord = classSymbol.IsRecord
            },
            TargetType = appliedTarget,
            TargetMemberName = targetMemberName,
            Arguments = attDict
        };
    }

    private void Generate(SourceProductionContext context, PluginFieldDefaultValuesInfo info) {
        if (info == default) return;

        var setToDefaultMethod = GenerateSetDataToDefaultMethod(info);

        var result = PartialClassTemplate
#if DEBUG
            .Replace("{{generatedAt}}", $" at {DateTime.Now}")
#else
            .Replace("{{generatedAt}}", string.Empty)
#endif
            .Replace("{{namespace}}", info.ClassInfo.NameSpace)
            .Replace("{{accessibility}}", info.ClassInfo.Accessibility.ToString().ToLower())
            .Replace("{{typeKind}}", info.ClassInfo.IsRecord ? "record" : string.Empty)
            .Replace("{{className}}", info.ClassInfo.Name)
            .Replace("{{method}}", setToDefaultMethod);

        context.AddSource($"{info.ClassInfo.Name}.g.cs", SourceText.From(result, Encoding.UTF8));
    }

    private string GenerateSetDataToDefaultMethod(PluginFieldDefaultValuesInfo info) {
        var builder = new StringBuilder();

        foreach (var kvp in info.Arguments) {
            var attName = kvp.Key;

            var template = attName switch {
                "PartFieldDefaultValuesAttribute" => PartSetToDefaultStatementsTemplate,
                "PlateFieldDefaultValuesAttribute" => PlateSetToDefaultStatementsTemplate,
                "WeldFieldDefaultValuesAttribute" => WeldSetToDefaultStatementsTemplate,
                "BoltFieldDefaultValuesAttribute" => BoltSetToDefaultStatementsTemplate,
                "BoltCircleFieldDefaultValuesAttribute" => BoltCircleSetToDefaultStatementsTemplate,
                _ => string.Empty
            };

            template = template.Replace("{{dataPropertyName.}}",
                info.TargetType == AttributeTargets.Class ? string.Empty : info.TargetMemberName + '.');

            var modelObjectName = attName.Substring(0, attName.Length - 27);
            modelObjectName = info.TargetType == AttributeTargets.Class
                ? ToPrivateFieldNameStyle(modelObjectName)
                : modelObjectName;

            foreach (var kvp2 in kvp.Value) {
                var nameOrNumber = kvp2.Key;

                var statements = template.Replace("{{modelObjectName}}", modelObjectName + nameOrNumber);

                var paramArgPair = kvp2.Value;
                foreach (var kvp3 in PresetValues[attName]) {
                    var paramName = kvp3.Key;
                    if (!paramArgPair.TryGetValue(paramName, out var argument)) {
                        argument = kvp3.Value;
                    }

                    statements = statements.Replace($"{{{{{paramName}Value}}}}", argument);
                }

                builder.AppendLine(statements);
            }
        }

        return SetDataToDefaultMethodTemplate.Replace("{{statements}}", builder.ToString());
    }
}