/*==============================================================================
 *  Muggle TsExtensions - extensions for Tekla Structures
 *
 *  Copyright © 2026 Huang YongXing.
 *
 *  This library is free software, licensed under the terms of the GNU
 *  General Public License as published by the Free Software Foundation,
 *  either version 3 of the License, or (at your option) any later version.
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *==============================================================================
 *  PluginFieldsGenerator.cs: help to generate fields and get field values method for plugin.
 *  written by Huang YongXing - thinkerhua@hotmail.com
 *==============================================================================*/

using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Muggle.TsExtensions.CodingHelper.Generators.Information;
using static Muggle.TsExtensions.CodingHelper.Generators.GeneratorHelper;

namespace Muggle.TsExtensions.CodingHelper.Generators;

[Generator]
public class PluginFieldsGenerator : IIncrementalGenerator {
    internal const string ConcernedAttribute = "Muggle.TsExtensions.CodingHelper.Generators.FieldsFromAttribute";

    #region Templates

    private const string PartialClassTemplate =
        """
        //  <auto-generated/>{{generatedAt}}

        namespace {{namespace}} {
            
            {{accessibility}} partial {{typeKind}}class {{className}} {
        {{fields}}
        {{methods}}
            }
        }

        """;

    private const string PluginFieldDeclareTemplate =
        """
                
                private {{datatype}} {{_modelObjectType}}{{NameOrNumber}}{{PropertyName}};
        """;

    private const string GetFieldValuesFromMethodTemplate =
        """
                
                /// <summary>
                /// Get field values from the given data.
                /// </summary>
                /// <param name="data">The given data.</param>
                private void GetFieldValuesFrom({{dataType}} data) {
        {{statements}}
                }
        """;

    #endregion

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(ctx => {
            var shortName = ConcernedAttribute.Substring(ConcernedAttribute.LastIndexOf('.') + 1);
            ctx.AddSource($"{shortName}.g.cs",
                SourceText.From(GetResourceAsString($"{shortName}.cs"), Encoding.UTF8));
        });

        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(ConcernedAttribute, Predicate, Transform)
            .Where(x => x != default);

        context.RegisterSourceOutput(provider, Generate);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken token) {
        if (token.IsCancellationRequested) return false;

        var classDeclarationSyntax = node as ClassDeclarationSyntax;

        return classDeclarationSyntax!.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    private static PluginFieldsInfo Transform(GeneratorAttributeSyntaxContext context, CancellationToken token) {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.TargetNode;
        var semanticModel = context.SemanticModel;

        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclarationSyntax);
        if (classSymbol == null) return default;

        var attSyntax = classDeclarationSyntax.AttributeLists.SelectMany(a => a.Attributes)
            .First(a => semanticModel.GetTypeInfo(a).Type?.ToDisplayString() == ConcernedAttribute);
        if (attSyntax.ArgumentList == null) return default;

        var dataTypeInfo = semanticModel.GetTypeInfo(attSyntax.ArgumentList.DescendantNodes()
            .OfType<TypeOfExpressionSyntax>().First().Type);
        if (dataTypeInfo.Type == null) return default;

        var dataAttSyntaxes = dataTypeInfo.Type.GetAttributes().Where(a =>
                PluginDataFieldsGenerator.ConcernedAttributes.Contains(a.AttributeClass?.ToDisplayString()))
            .Select(a => a.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax);

        var argDict = new ArgumentsDictionary<NameOrNumberSet>();

        foreach (var dataAttSyntax in dataAttSyntaxes) {
            var attTypeInfo = semanticModel.GetTypeInfo(dataAttSyntax!, token);
            var attName = attTypeInfo.Type?.ToDisplayString();
            attName = attName!.Substring(attName.LastIndexOf('.') + 1);

            var args = dataAttSyntax.ArgumentList!.Arguments
                .SelectMany(attArgSyntax => attArgSyntax.DescendantNodes().OfType<LiteralExpressionSyntax>())
                .Select(exprSyntax => exprSyntax.Token.ValueText);

            var argSet = new NameOrNumberSet();
            foreach (var arg in args) { argSet.Add(arg); }

            argDict.Add(attName, argSet);
        }

        token.ThrowIfCancellationRequested();

        return new PluginFieldsInfo {
            ClassInfo = new ClassInfo {
                Name = classDeclarationSyntax.Identifier.ValueText,
                NameSpace = classSymbol.ContainingNamespace.ToDisplayString(),
                Accessibility = classSymbol.DeclaredAccessibility,
                IsRecord = classSymbol.IsRecord,
            },
            DataType = dataTypeInfo.Type,
            Arguments = argDict
        };

    }

    private static void Generate(SourceProductionContext context, PluginFieldsInfo info) {
        if (info == default) return;

        var fields = GenerateFields(info);
        var method = GenerateGetFieldValuesFromMethod(info);

        var result = PartialClassTemplate
#if DEBUG
            .Replace("{{generatedAt}}", $" at {DateTime.Now}")
#else
            .Replace("{{generatedAt}}", string.Empty)
#endif
            .Replace("{{namespace}}", info.ClassInfo.NameSpace)
            .Replace("{{accessibility}}", info.ClassInfo.Accessibility.ToString().ToLower())
            .Replace("{{typeKind}}", info.ClassInfo.IsRecord ? "record" : string.Empty)
            .Replace("{{className}}", info.ClassInfo.Name)
            .Replace("{{fields}}", fields)
            .Replace("{{methods}}", method);

        context.AddSource($"{info.ClassInfo.Name}.g.cs", SourceText.From(result, Encoding.UTF8));
    }

    private static string GenerateFields(PluginFieldsInfo info) {
        var builder = new StringBuilder();

        var fieldSymbols = info.DataType.GetMembers().OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Public);

        foreach (var fieldSymbol in fieldSymbols) {
            var fieldName = ToPrivateFieldNameStyle(fieldSymbol.Name);
            builder.AppendLine("        ");
            builder.AppendLine($"        private {fieldSymbol.Type} {fieldName};");
        }

        foreach (var kvp in info.Arguments) {
            var attName = kvp.Key;

            var _modelObjectType = ToPrivateFieldNameStyle(attName.Substring(0, attName.Length - 15));
            var template = PluginFieldDeclareTemplate.Replace("{{_modelObjectType}}", _modelObjectType);

            var fieldInfos = attName switch {
                "PartFieldsAttribute" => PluginDataFieldsGenerator.PartFieldInfos,
                "PlateFieldsAttribute" => PluginDataFieldsGenerator.PlateFieldInfos,
                "WeldFieldsAttribute" => PluginDataFieldsGenerator.WeldFieldInfos,
                "BoltFieldsAttribute" => PluginDataFieldsGenerator.BoltFieldInfos,
                "BoltCircleFieldsAttribute" => PluginDataFieldsGenerator.BoltCircleFieldInfos,
                _ => []
            };

            var templateBuilder = new StringBuilder();
            foreach (var fieldInfo in fieldInfos) {
                templateBuilder.AppendLine(template
                    .Replace("{{datatype}}", fieldInfo.Type)
                    .Replace("{{PropertyName}}", fieldInfo.Name));
            }

            template = templateBuilder.ToString();

            foreach (var nameOrNumber in kvp.Value) {
                builder.Append(template.Replace("{{NameOrNumber}}", nameOrNumber));
            }
        }

        return builder.ToString();
    }

    private static string GenerateGetFieldValuesFromMethod(PluginFieldsInfo info) {

        var builder = new StringBuilder();

        var template = "            {{privateFieldName}} = data.{{publicFieldName}};";

        var fieldSymbols = info.DataType.GetMembers().OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Public);

        foreach (var fieldSymbol in fieldSymbols) {
            var privateFieldName = ToPrivateFieldNameStyle(fieldSymbol.Name);
            builder.AppendLine(template
                .Replace("{{privateFieldName}}", privateFieldName)
                .Replace("{{publicFieldName}}", fieldSymbol.Name));
        }

        foreach (var kvp in info.Arguments) {
            var attName = kvp.Key;

            var modelObjectType = attName.Substring(0, attName.Length - 15);

            var fieldInfos = attName switch {
                "PartFieldsAttribute" => PluginDataFieldsGenerator.PartFieldInfos,
                "PlateFieldsAttribute" => PluginDataFieldsGenerator.PlateFieldInfos,
                "WeldFieldsAttribute" => PluginDataFieldsGenerator.WeldFieldInfos,
                "BoltFieldsAttribute" => PluginDataFieldsGenerator.BoltFieldInfos,
                "BoltCircleFieldsAttribute" => PluginDataFieldsGenerator.BoltCircleFieldInfos,
                _ => []
            };

            var templateBuilder = new StringBuilder();
            templateBuilder.AppendLine("            ");
            foreach (var fieldInfo in fieldInfos) {
                templateBuilder.AppendLine(
                    $"            {ToPrivateFieldNameStyle(modelObjectType)}{{{{nameOrNumber}}}}" +
                    $"{fieldInfo.Name} = data.{modelObjectType}{{{{nameOrNumber}}}}{fieldInfo.Name};");
            }

            template = templateBuilder.ToString();

            foreach (var nameOrNumber in kvp.Value) {
                builder.Append(template.Replace("{{nameOrNumber}}", nameOrNumber));
            }
        }

        return GetFieldValuesFromMethodTemplate
            .Replace("{{dataType}}", info.DataType.ToString())
            .Replace("{{statements}}", builder.ToString());
    }
}