<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<LangVersion>Latest</LangVersion>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<AssemblyName>Muggle.TsExtensions</AssemblyName>
		<RootNamespace>Muggle.TsExtensions.MainWindow</RootNamespace>
		<Authors>thinkerhua@hotmail.com</Authors>
		<Copyright>Copyright © 2024 thinkerhua@hotmail.com. All rights reserved.</Copyright>
		<ApplicationIcon>Resources\logo.ico</ApplicationIcon>
		<Configurations>D2021;D2024;R2021;R2024</Configurations>
        <Optimize Condition="$(Configuration.StartsWith('R'))">True</Optimize>
        <DefineConstants Condition="$(Configuration.StartsWith('D'))">TRACE;DEBUG</DefineConstants>
        <DefineConstants Condition="$(Configuration.StartsWith('R'))">TRACE;RELEASE</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="CalcBinding" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Tekla.Structures" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Catalogs" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Datatype" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Dialog" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Model" ExcludeAssets="runtime" />
		<PackageReference Include="Tekla.Structures.Plugins" ExcludeAssets="runtime" />
		<PackageReference Include="TSAppConfigPatcherTask" Condition="$(Configuration.EndsWith('2024'))"/>
	</ItemGroup>
	
	<ItemGroup>
		<Reference Include="PresentationFramework.Aero2" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Common.WPF\Common.WPF.csproj" />
		<ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\logo.ico" />
		<Resource Include="Resources\logo.ico" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(TargetDir)$(TargetName).exe&quot; &quot;D:\Program Files\Tekla Structures\$(TeklaVersion)\Environments\common\extensions\Muggle.TsExtensions\&quot; /Y /C /Q /R" />
	</Target>
</Project>