<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Muggle.TsExtensions.CodingHelper</RootNamespace>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <PackageId>Muggle.TsExtensions.CodingHelper</PackageId>
        <Title>Tekla Structures OpenAPI development helper</Title>
        <Version>1.3.1</Version>
        <Authors>Huang YongXing</Authors>
        <Description>Help to generate fields (with StructuresFieldAttribute) for plugin data, fields for plugin, and properties (with StructuresDialogAttribute) for view model which used by plugin WPF UI.</Description>
        <Copyright>© 2026 Huang YongXing</Copyright>
        <PackageIcon>Assets/logo.png</PackageIcon>
        <PackageProjectUrl>https://github.com/ThinkerHua/Muggle-Tekla-Structures-Extensions</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/ThinkerHua/Muggle-Tekla-Structures-Extensions.git</RepositoryUrl>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <PackageTags>Tekla Structures OpenAPI Generator</PackageTags>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>Improve diagnoser for the new properties generator.</PackageReleaseNotes>
        <IncludeBuildOutput>false</IncludeBuildOutput>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets/logo.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Update="Readme.md">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="$(OutputPath)/$(AssemblyName).dll">
            <Pack>True</Pack>
            <PackagePath>analyzers/dotnet/cs</PackagePath>
            <Visible>false</Visible>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Resources\BoltCircleFieldDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\BoltCircleFieldsAttribute.cs" />
        <Compile Remove="Resources\BoltCirclePropertiesAttribute.cs" />
        <Compile Remove="Resources\BoltCirclePropertiesWithDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\BoltFieldDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\BoltFieldsAttribute.cs" />
        <Compile Remove="Resources\BoltPropertiesAttribute.cs" />
        <Compile Remove="Resources\BoltPropertiesWithDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\ConnectionViewModel.cs" />
        <Compile Remove="Resources\DetailViewModel.cs" />
        <Compile Remove="Resources\FieldsFromAttribute.cs" />
        <Compile Remove="Resources\NotificationObject.cs" />
        <Compile Remove="Resources\PartFieldDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\PartFieldsAttribute.cs" />
        <Compile Remove="Resources\PartPropertiesAttribute.cs" />
        <Compile Remove="Resources\PartPropertiesWithDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\PlateFieldDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\PlateFieldsAttribute.cs" />
        <Compile Remove="Resources\PlatePropertiesAttribute.cs" />
        <Compile Remove="Resources\PlatePropertiesWithDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\WeldFieldDefaultValuesAttribute.cs" />
        <Compile Remove="Resources\WeldFieldsAttribute.cs" />
        <Compile Remove="Resources\WeldPropertiesAttribute.cs" />
        <Compile Remove="Resources\WeldPropertiesWithDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltCircleFieldDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltCircleFieldsAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltCirclePropertiesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltCirclePropertiesWithDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltFieldDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltFieldsAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltPropertiesAttribute.cs" />
        <EmbeddedResource Include="Resources\BoltPropertiesWithDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\ConnectionViewModel.cs" />
        <EmbeddedResource Include="Resources\DetailViewModel.cs" />
        <EmbeddedResource Include="Resources\FieldsFromAttribute.cs" />
        <EmbeddedResource Include="Resources\NotificationObject.cs" />
        <EmbeddedResource Include="Resources\PartFieldDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\PartFieldsAttribute.cs" />
        <EmbeddedResource Include="Resources\PartPropertiesAttribute.cs" />
        <EmbeddedResource Include="Resources\PartPropertiesWithDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\PlateFieldDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\PlateFieldsAttribute.cs" />
        <EmbeddedResource Include="Resources\PlatePropertiesAttribute.cs" />
        <EmbeddedResource Include="Resources\PlatePropertiesWithDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\WeldFieldDefaultValuesAttribute.cs" />
        <EmbeddedResource Include="Resources\WeldFieldsAttribute.cs" />
        <EmbeddedResource Include="Resources\WeldPropertiesAttribute.cs" />
        <EmbeddedResource Include="Resources\WeldPropertiesWithDefaultValuesAttribute.cs" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="AnalyzerReleases.Unshipped.md" />
      <AdditionalFiles Remove="AnalyzerReleases.Shipped.md" />
    </ItemGroup>

</Project>
