<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Muggle.TsExtensions.CodingHelper</RootNamespace>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<PackageId>Muggle.TsExtensions.CodingHelper</PackageId>
		<Title>Tekla Structures OpenAPI development helper</Title>
		<Version>1.2.1</Version>
		<Authors>Huang YongXing</Authors>
		<Description>Help to generate fields (with StructuresFieldAttribute) for plugin data, fields for plugin, and properties (with StructuresDialogAttribute) for view model which used by plugin WPF UI.</Description>
		<Copyright>© 2026 Huang YongXing</Copyright>
		<PackageIcon>Assets/logo.png</PackageIcon>
		<PackageProjectUrl>https://github.com/ThinkerHua/Muggle-Tekla-Structures-Extensions</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/ThinkerHua/Muggle-Tekla-Structures-Extensions.git</RepositoryUrl>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
		<PackageTags>Tekla Structures OpenAPI Generator</PackageTags>
		<PackageReleaseNotes>Fix the issue where the analyzers are not actually working.</PackageReleaseNotes>
		<PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Assets/logo.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Update="Readme.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="$(OutputPath)/$(AssemblyName).dll">
			<Pack>True</Pack>
			<PackagePath>analyzers/dotnet/cs</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

</Project>
