/*==============================================================================
 *  Muggle Tekla-Plugins - tools and plugins for Tekla Structures
 *
 *  Copyright © 2024 Huang YongXing.                 
 *
 *  This library is free software, licensed under the terms of the GNU 
 *  General Public License as published by the Free Software Foundation, 
 *  either version 3 of the License, or (at your option) any later version. 
 *  You should have received a copy of the GNU General Public License 
 *  along with this program. If not, see <http://www.gnu.org/licenses/>. 
 *==============================================================================
 *  MatrixExtension.cs: extension of Tekla.Structures.Geometry3d.Matrix
 *  written by Huang YongXing - thinkerhua@hotmail.com
 *==============================================================================*/
using System;
using Tekla.Structures.Geometry3d;

namespace Muggle.TeklaPlugins.Common.Geometry3d {

    /// <summary>
    /// <see cref="Tekla.Structures.Geometry3d"/>.<see cref="Matrix"/> 的扩展。
    /// </summary>
    public static class MatrixExtension {

        /// <summary>
        /// 计算矩阵的行列式。
        /// </summary>
        /// <remarks><b>* 非方阵行列式未定义，此处忽略矩阵的平移部分。</b></remarks>
        /// <returns>矩阵（线性变换部分）的行列式。</returns>
        /// <param name="matrix">当前矩阵</param>
        /// <exception cref="ArgumentNullException"></exception>
        public static double Determinant(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            double det = 0;

            // det = M00 * M11 * M22 + M01 * M12 * M20 + M02 * M10 * M21
            //      -M00 * M12 * M21 - M01 * M10 * M22 - M02 * M11 * M20
            for (int i = 0; i < 3; i++) {
                det += matrix[0, (i + 0) % 3] * matrix[1, (i + 1) % 3] * matrix[2, (i + 2) % 3]
                     - matrix[0, (i + 0) % 3] * matrix[1, (i + 2) % 3] * matrix[2, (i + 1) % 3];
            }

            return det;
        }

        /// <summary>
        /// 克莱姆法则求解线性方程组。
        /// </summary>
        /// <remarks>线性方程组的系数项以列向量形式储存在矩阵的线性变换部分中，
        /// 常数项以行向量形式储存在矩阵的平移部分中。</remarks>
        /// <param name="matrix">当前矩阵</param>
        /// <returns>以点的形式返回方程组的解。无解则返回null。</returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static Point Cramer(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            var m = new Matrix(matrix);
            var det = m.Determinant();
            if (det == 0) return null;

            for (int i = 0; i < 3; i++) {
                m[i, 0] = matrix[3, i];
            }
            var det1 = m.Determinant();

            for (int i = 0; i < 3; i++) {
                m[i, 0] = matrix[i, 0];
                m[i, 1] = matrix[3, i];
            }
            var det2 = m.Determinant();

            for (int i = 0; i < 3; i++) {
                m[i, 1] = matrix[i, 1];
                m[i, 2] = matrix[3, i];
            }
            var det3 = m.Determinant();

            return new Point(det1 / det, det2 / det, det3 / det);
        }

        /// <summary>
        /// [Generated by Copilot]
        /// Returns the inverse of the specified matrix.
        /// </summary>
        /// <remarks>This method is intended for use with invertible matrices only. If the matrix is not
        /// invertible (i.e., its determinant is zero), an exception is thrown. The returned matrix is a new instance;
        /// the original matrix is not modified.</remarks>
        /// <param name="matrix">The matrix to invert. Must be non-null and non-singular.</param>
        /// <returns>A new Matrix instance representing the inverse of the specified matrix.</returns>
        /// <exception cref="ArgumentNullException">Thrown if the matrix parameter is null.</exception>
        /// <exception cref="InvalidOperationException">Thrown if the matrix is singular and cannot be inverted.</exception>
        public static Matrix Inverse(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }
            var det = matrix.Determinant();
            if (det == 0) {
                throw new InvalidOperationException("Matrix is singular and cannot be inverted.");
            }
            var m = new Matrix();
            //计算伴随矩阵
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    m[j, i] = ((matrix[(i + 1) % 3, (j + 1) % 3] * matrix[(i + 2) % 3, (j + 2) % 3])
                             - (matrix[(i + 1) % 3, (j + 2) % 3] * matrix[(i + 2) % 3, (j + 1) % 3])) / det;
                }
            }
            //计算平移部分
            for (int i = 0; i < 3; i++) {
                m[3, i] = -(m[0, i] * matrix[3, 0] + m[1, i] * matrix[3, 1] + m[2, i] * matrix[3, 2]);
            }
            return m;
        }

        /*/// <summary>
        /// [gamemath.com]
        /// Returns the inverse of the specified matrix.
        /// </summary>
        /// <param name="matrix"></param>
        /// <returns></returns>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="InvalidOperationException"></exception>
        public static Matrix Inverse(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            var det = matrix.Determinant();
            if (det == 0) {
                throw new InvalidOperationException("Matrix is singular and cannot be inverted.");
            }

            var r = new Matrix();
            r[0, 0] = (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]) / det;
            r[0, 1] = (matrix[0, 2] * matrix[2, 1] - matrix[0, 1] * matrix[2, 2]) / det;
            r[0, 2] = (matrix[0, 1] * matrix[1, 2] - matrix[0, 2] * matrix[1, 1]) / det;
            r[1, 0] = (matrix[1, 2] * matrix[2, 0] - matrix[1, 0] * matrix[2, 2]) / det;
            r[1, 1] = (matrix[0, 0] * matrix[2, 2] - matrix[0, 2] * matrix[2, 0]) / det;
            r[1, 2] = (matrix[0, 2] * matrix[1, 0] - matrix[0, 0] * matrix[1, 2]) / det;
            r[2, 0] = (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0]) / det;
            r[2, 1] = (matrix[0, 1] * matrix[2, 0] - matrix[0, 0] * matrix[2, 1]) / det;
            r[2, 2] = (matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]) / det;
            r[3, 0] = -(matrix[3, 0] * r[0, 0] + matrix[3, 1] * r[1, 0] + matrix[3, 2] * r[2, 0]);
            r[3, 1] = -(matrix[3, 0] * r[0, 1] + matrix[3, 1] * r[1, 1] + matrix[3, 2] * r[2, 1]);
            r[3, 2] = -(matrix[3, 0] * r[0, 2] + matrix[3, 1] * r[1, 2] + matrix[3, 2] * r[2, 2]);

            return r;
        }*/

        /// <summary>
        /// 使用当前矩阵变换给定向量。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <param name="vector">给定向量</param>
        /// <returns>变换后的向量。</returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static Vector Transform(this Matrix matrix, Vector vector) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            if (vector is null) {
                throw new ArgumentNullException(nameof(vector));
            }

            //对于向量，可以只使用矩阵的旋转部分进行变换
            //也可使用完整矩阵对表示向量的点和零点进行变换后，生成新向量
            var head = matrix.Transform(vector);
            var tail = matrix.Transform(new Point());

            return new Vector(head - tail);
        }

        /// <summary>
        /// 使用当前矩阵变换给定坐标系。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <param name="coordinateSystem">给定坐标系</param>
        /// <returns>转换后的坐标系，X轴、Y轴向量标准化为 1000。</returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static CoordinateSystem Transform(this Matrix matrix, CoordinateSystem coordinateSystem) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            if (coordinateSystem is null) {
                throw new ArgumentNullException(nameof(coordinateSystem));
            }

            var transposed = matrix.GetTranspose();

            var origin = transposed.Transform(coordinateSystem.Origin);
            var axisX = Transform(transposed, coordinateSystem.AxisX);
            var axisY = Transform(transposed, coordinateSystem.AxisY);
            axisX.Normalize(1000);
            axisY.Normalize(1000);

            return new CoordinateSystem(origin, axisX, axisY);
        }

        /// <summary>
        /// 移除当前矩阵的平移部分，即仅保留旋转部分。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <exception cref="ArgumentNullException"></exception>
        public static void RemoveTranslation(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            matrix[3, 0] = matrix[3, 1] = matrix[3, 2] = 0;
        }

        /// <summary>
        /// 移除当前矩阵的旋转部分，即仅保留平移部分。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <exception cref="ArgumentNullException"></exception>
        public static void RemoveRotation(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            var transposed = matrix.GetTranspose();
            var rotation = matrix.GetRotationPart();
            var translation = (transposed * rotation).GetTranspose();

            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 2; j++) {
                    matrix[i, j] = translation[i, j];
                }
            }
        }

        /// <summary>
        /// 获取当前矩阵旋转部分的新矩阵。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <returns>矩阵旋转部分的新矩阵。</returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static Matrix GetRotationPart(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            var m = new Matrix(matrix);
            m.RemoveTranslation();

            return m;
        }

        /// <summary>
        /// 获取当前矩阵平移部分的新矩阵。
        /// </summary>
        /// <param name="matrix">当前矩阵</param>
        /// <returns>矩阵平移部分的新矩阵。</returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static Matrix GetTranslationPart(this Matrix matrix) {
            if (matrix is null) {
                throw new ArgumentNullException(nameof(matrix));
            }

            var m = new Matrix(matrix);
            m.RemoveRotation();

            return m;
        }
    }
}
